networks:
  default:
    name: landing
    driver: overlay
    attachable: true

services:
  landing-api:
    image: skulpture/landing-api:${TAG:-latest}
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_SERVICE_NAME: landing-api
      GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID}
      GSHEETS_SPREADSHEET_ID: ${GSHEETS_SPREADSHEET_ID}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}"
      POSTMARK_TEMPLATE: ${POSTMARK_TEMPLATE}
      POSTMARK_SERVER_TOKEN: ${POSTMARK_SERVER_TOKEN}
      POSTMARK_ACCOUNT_TOKEN: ${POSTMARK_ACCOUNT_TOKEN}
      GO_ENV: ${GO_ENV}
    deploy:
      mode: replicated
      replicas: 2
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
