secrets:
  proxy.certificate:
    file: ${PROXY_CERT_PATH}
  proxy.key:
    file: ${PROXY_KEY_PATH}

services:
  proxy:
    image: nginx:alpine
    ports:
      - target: 443
        published: 443
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    networks:
      - landing
    ulimits:
      nofile:
        soft: 20000
        hard: 20000

networks:
  landing:
    external: true
