services:
  landing-api:
    image: golang:alpine
    command: cd app && go run
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/credentials.json
      - ./:/app
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_SERVICE_NAME: landing-api
      GDRIVE_FOLDER_ID: ${TEST_GDRIVE_FOLDER_ID}
      GSHEETS_SPREADSHEET_ID: ${TEST_GSHEETS_SPREADSHEET_ID}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}"
      POSTMARK_TEMPLATE: ${TEST_POSTMARK_TEMPLATE}
      POSTMARK_SERVER_TOKEN: ${TEST_POSTMARK_SERVER_TOKEN}
      POSTMARK_ACCOUNT_TOKEN: ${TEST_POSTMARK_ACCOUNT_TOKEN}
      GO_ENV: "test"
      GOOGLE_APPLICATION_CREDENTIALS: /credentials.json
