networks:
  default:
    name: landing
    driver: overlay
    attachable: true

secrets:
  proxy.certificate:
    file: ${PROXY_CERT_PATH}
  proxy.key:
    file: ${PROXY_KEY_PATH}

services:
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - target: 443
        published: 443
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
    depends_on:
      - landing-api-prod
      - landing-api-dev

  landing-api-prod:
    image: skulpture/landing-api:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_SERVICE_NAME: landing-api-prod
      GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID}
      GSHEETS_SPREADSHEET_ID: ${GSHEETS_SPREADSHEET_ID}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}"
      POSTMARK_TEMPLATE: ${POSTMARK_TEMPLATE}
      POSTMARK_SERVER_TOKEN: ${POSTMARK_SERVER_TOKEN}
      POSTMARK_ACCOUNT_TOKEN: ${POSTMARK_ACCOUNT_TOKEN}
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY}
      GO_ENV: "production"
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost || exit 1" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s

  landing-api-dev:
    image: skulpture/landing-api:dev
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_SERVICE_NAME: landing-api-dev
      GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID_DEV}
      GSHEETS_SPREADSHEET_ID: ${GSHEETS_SPREADSHEET_ID_DEV}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}"
      POSTMARK_TEMPLATE: ${POSTMARK_TEMPLATE_DEV}
      POSTMARK_SERVER_TOKEN: ${POSTMARK_SERVER_TOKEN}
      POSTMARK_ACCOUNT_TOKEN: ${POSTMARK_ACCOUNT_TOKEN}
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY}
      GO_ENV: "development"
      FRONTEND_URL: "https://dev.skulpture-xyz.pages.dev"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost || exit 1" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
