name: LLM Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  pr_agent_jobs:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    
    steps:
      - name: Review pull request
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.model: "gpt-4o-mini"
          config.model_turbo: "gpt-4o"
          config.fallback_models: "gpt-4o"
          pr_reviewer.require_score_review: true
          pr_description.publish_labels: false
          pr_description.publish_description_as_comment: true
          pr_code_suggestions.rank_suggestions: true
