name: Release

on:
  pull_request:
    branches: [master] #, staging
    types: [closed]
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'dev' #${{ env.BRANCH_NAME == 'master' && 'dev' }}

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}
    
      # For most cases: https://github.com/actions-ecosystem/action-push-tag will suffice
      # The action currently fails if the repository uses GIT LFS
      - name: Push tags
        run: |
          git tag ${{ steps.bump-semver.outputs.new_version }}
          git push origin --no-verify --tag

      - uses: softprops/action-gh-release@v2
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          # prerelease: ${{ env.BRANCH_NAME == 'dev' && false || true }}
          name: ${{ steps.bump-semver.outputs.new_version }}
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          target_commitish: dev #${{ env.BRANCH_NAME == 'master' && 'dev' || 'dev' }}
          generate_release_notes: true
