name: Test services

on:
  push:
    # branches: [master, staging, dev]
  workflow_dispatch:

jobs:
  up:
    environment: "test"

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure GCP credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          token_format: "access_token"
          access_token_scopes: |
            https://www.googleapis.com/auth/cloud-platform
            https://www.googleapis.com/auth/drive
            https://www.googleapis.com/auth/spreadsheets

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Test API
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose_file: "./api/docker-compose.yml"
          test-container: "landing-api"
          test-command: "go test"
        env:
          LOG_LEVEL: "DEBUG"
          OTEL_SERVICE_NAME: "landing-api-test"
          TEST_GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          TEST_GSHEETS_SPREADSHEET_ID: ${{ secrets.GSHEETS_SPREADSHEET_ID }}
          OTEL_EXPORTER_OTLP_ENDPOINT: ""
          OTEL_EXPORTER_OTLP_AUTH_TOKEN: ""
          TEST_POSTMARK_TEMPLATE: ""
          TEST_POSTMARK_SERVER_TOKEN: ""
          TEST_POSTMARK_ACCOUNT_TOKEN: ""
          GO_ENV: "production"
